<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
require APPPATH . '/libraries/BaseController.php';
class District extends BaseController{
    function __construct()
    {
        parent::__construct();
        $this->load->model('District_model');
        $this->load->model('user_model');
        $this->load->database();
        $this->isLoggedIn();
    } 

    /*
     * Listing of district
     */
    function index()
    {
        $data['district'] = $this->District_model->get_all_district();

        
       // $data['district_admin'] = $this->District_model->get_district_admin($data['user_id']);
        
        $data['_view'] = 'district/index';
       // $this->load->view('layouts/main',$data);
        $this->loadViews('district/index', $this->global, $data , NULL);
    }

    /*
     * Adding a new district
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'district_name' => $this->input->post('district_name'),
            );
            
            $district_id = $this->District_model->add_district($params);
            redirect('district/index');
        }
        else
            $this->loadViews('district/add', $this->global, NULL, NULL);
        }

    /*
     * Editing a district
     */
    function edit($district_id)
    {   
        // check if the district exists before trying to edit it
        $data['district'] = $this->District_model->get_district($district_id);
        
        if(isset($data['district']['district_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'district_name' => $this->input->post('district_name'),
                );

                $this->District_model->update_district($district_id,$params);            
                redirect('district/index');
            }
            else
            {
                $this->loadViews('district/edit', $this->global, $data , NULL);
            }
        }
        else
            show_error('The district you are trying to edit does not exist.');
    } 

    /*
     * Deleting district
     */
    function remove($district_id)
    {
        $district = $this->District_model->get_district($district_id);

        // check if the district exists before trying to delete it
        if(isset($district['district_id']))
        {
            $this->District_model->delete_district($district_id);
            redirect('district/index');
        }
        else
            show_error('The district you are trying to delete does not exist.');
    }
    

}